Task : find square root from given numbers</br>
use of try catch block for error handling</br>
Test Cases
- test 1 : given 4 then result is 2
- test 2 : given 0 then result is 0
- test 3 : given 2 then result is 1.41421356237
- test 4 : given -1 then result is that the program exits with "Domain error" message